### ISSUE TITLE
Move to SciKit-Surgery org

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgerytorch#11]

**Comment by mxochicale** [comment]
Hi @thompson318 

Any plans for this one? to keep a consistency naming of organisations of the repos in https://github.com/SciKit-Surgery

Happy to migrate repo and issues. I have done something similar in the pass following https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository , https://docs.github.com/en/enterprise-server@3.3/repositories/creating-and-managing-repositories/transferring-a-repository

Thanks

**Comment by thompson318** [comment]
Thanks @mxochicale, yes please see if you can do this.

**Comment by mxochicale** [comment]
Hi @thompson318 
I think I need permissions to go into settings and Transfer ownership from different organisations. 
Would you please check it. 
Thanks

**Comment by thompson318** [comment]
OK, try now.

**Comment by mxochicale** [comment]
Thanks!
Successful transfer from https://github.com/UCL/scikit-surgerytorch to  https://github.com/SciKit-Surgery/scikit-surgerytorch/
No need to transfer issues/PRs.
